tic;
clear;clc;
%初始化
%全局期望路径为曲线时输入（第一步：全局期望路径的构建，车辆状态、位置信息的获取）
L=10;%预瞄距离（有时间可以考虑其随速度变化，P控制）
l=2.5;t=1;
figure(1)
%车辆状态信息的获取
%假定初始车头朝向与x轴平行
[theta,x_v,y_v,V]=StateOfVehicle();scatter(x_v,y_v,'b*')
pa=waypoints();%表示全局路径与大地坐标系初始倾角%参考路径
x_G=0:5:50;y_G=pa(1)*x_G.^3+pa(2)*x_G.^2+pa(3)*x_G+pa(4);
theta_Gpath=3*pa(1)*x_G.^2+2*pa(2)*x_G+pa(3);
hold on
%候选路径的生成（第二步：候选路径集的生成）
[x_Candidate,y_Candidate,deta_control]=PathCandidatesGeneration_G(L,l,V,t,x_v,y_v,theta,theta_Gpath,x_G,y_G);
%障碍物信息（第三步：路径选择）
[x_Ob,y_Ob]=obstacle();
%碰撞风险分析
[collision_lateral,collision_longitu]=CollisionCheck(x_Candidate,x_Ob,y_Candidate,y_Ob,V,x_v);
collision=collision_lateral+collision_longitu;
%偏差成本分析
offset=OffsetCheck();
%成本整合
w_s=0.6;w_o=0.4;
cost=w_s*collision+w_o*offset;
%路径选择
PathCandidate=PathSelect(cost,x_v,y_v,x_Candidate,y_Candidate);
plot(x_Candidate(:,PathCandidate),y_Candidate(:,PathCandidate),'color','b','linewidth',5);
%车辆状态更新
%车辆输出量
deta_control=deta_control(:,PathCandidate);
toc